import type { RequestRecord } from "./RequestTypes";

// React Query에서 사용할 쿼리 키 정의
export const requestKeys = {
  records: ["request", "records"] as const,
};

// 발주 요청 목데이터
export const requestRecords: RequestRecord[] = [
  {
    requestId: "REQ-251001-01",
    requestDate: "2025-10-01 09:30",
    agency: "서울자동차부품상사",
    agencyLocation: "서울특별시 강남구",
    manager: "김민수",
    managerPosition: "영업팀장",
    managerContact: "010-1234-5678",
    submissionDate: "2025-10-01 10:00",
    status: "승인",
    remarks: "긴급 발주",
    inventoryItems: [
      {
        inventoryCode: "ENG-101",
        inventoryName: "엔진블록",
        requestQuantity: 2,
      },
      {
        inventoryCode: "FLT-305",
        inventoryName: "오일필터",
        requestQuantity: 10,
      },
    ],
  },
  {
    requestId: "REQ-251001-02",
    requestDate: "2025-10-01 14:20",
    agency: "부산카서비스",
    agencyLocation: "부산광역시 해운대구",
    manager: "이수진",
    managerPosition: "대리",
    managerContact: "010-8765-4321",
    submissionDate: "2025-10-01 15:00",
    status: "미승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "BRK-210",
        inventoryName: "브레이크패드",
        requestQuantity: 8,
      },
      {
        inventoryCode: "BRK-215",
        inventoryName: "브레이크디스크",
        requestQuantity: 4,
      },
      {
        inventoryCode: "BOL-101",
        inventoryName: "조립볼트세트",
        requestQuantity: 20,
      },
    ],
  },
  {
    requestId: "REQ-251002-03",
    requestDate: "2025-10-02 09:00",
    agency: "대구모터스",
    agencyLocation: "대구광역시 북구",
    manager: "정다은",
    managerPosition: "매니저",
    managerContact: "010-2222-3333",
    submissionDate: "2025-10-02 09:40",
    status: "승인",
    remarks: "정기 발주",
    inventoryItems: [
      {
        inventoryCode: "SPK-501",
        inventoryName: "냉각수호스",
        requestQuantity: 30,
      },
      {
        inventoryCode: "BLT-401",
        inventoryName: "벨트세트",
        requestQuantity: 5,
      },
    ],
  },
  {
    requestId: "REQ-251002-04",
    requestDate: "2025-10-02 13:10",
    agency: "인천오토월드",
    agencyLocation: "인천광역시 미추홀구",
    manager: "박정훈",
    managerPosition: "부장",
    managerContact: "010-4444-5555",
    submissionDate: "2025-10-02 13:30",
    status: "반려",
    remarks: "재고 부족",
    inventoryItems: [
      {
        inventoryCode: "ENG-220",
        inventoryName: "연료펌프",
        requestQuantity: 3,
      },
      {
        inventoryCode: "FLD-111",
        inventoryName: "냉각수호스",
        requestQuantity: 12,
      },
    ],
  },
  {
    requestId: "REQ-251003-05",
    requestDate: "2025-10-03 11:40",
    agency: "광주모터샵",
    agencyLocation: "광주광역시 서구",
    manager: "최유진",
    managerPosition: "점장",
    managerContact: "010-9999-1111",
    submissionDate: "2025-10-03 12:10",
    status: "승인",
    remarks: "테스트용 부품 포함",
    inventoryItems: [
      {
        inventoryCode: "PST-112",
        inventoryName: "피스톤세트",
        requestQuantity: 4,
      },
      {
        inventoryCode: "CRK-301",
        inventoryName: "크랭크샤프트",
        requestQuantity: 1,
      },
    ],
  },
  {
    requestId: "REQ-251004-06",
    requestDate: "2025-10-04 10:00",
    agency: "울산오토하우스",
    agencyLocation: "울산광역시 남구",
    manager: "한지훈",
    managerPosition: "기술팀장",
    managerContact: "010-5555-7777",
    submissionDate: "2025-10-04 10:20",
    status: "미승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "WTR-602",
        inventoryName: "워터펌프",
        requestQuantity: 2,
      },
      {
        inventoryCode: "RAD-701",
        inventoryName: "라디에이터",
        requestQuantity: 1,
      },
    ],
  },
  {
    requestId: "REQ-251004-07",
    requestDate: "2025-10-04 15:45",
    agency: "수원카테크",
    agencyLocation: "경기도 수원시",
    manager: "오지민",
    managerPosition: "과장",
    managerContact: "010-8888-9999",
    submissionDate: "2025-10-04 16:00",
    status: "승인",
    remarks: "정기 점검 부품",
    inventoryItems: [
      {
        inventoryCode: "AIR-202",
        inventoryName: "에어필터",
        requestQuantity: 15,
      },
      {
        inventoryCode: "OIL-203",
        inventoryName: "오일필터",
        requestQuantity: 15,
      },
      {
        inventoryCode: "CAB-204",
        inventoryName: "캐빈필터",
        requestQuantity: 10,
      },
    ],
  },
  {
    requestId: "REQ-251005-08",
    requestDate: "2025-10-05 09:20",
    agency: "창원모터스",
    agencyLocation: "경상남도 창원시",
    manager: "이하늘",
    managerPosition: "주임",
    managerContact: "010-1212-3434",
    submissionDate: "2025-10-05 09:50",
    status: "승인",
    remarks: "-",
    inventoryItems: [
      {
        inventoryCode: "SPK-501",
        inventoryName: "스파크플러그",
        requestQuantity: 20,
      },
    ],
  },
  {
    requestId: "REQ-251006-09",
    requestDate: "2025-10-06 13:25",
    agency: "평택자동차정비",
    agencyLocation: "경기도 평택시",
    manager: "문세린",
    managerPosition: "정비반장",
    managerContact: "010-7777-3333",
    submissionDate: "2025-10-06 13:45",
    status: "반려",
    remarks: "수량 과다",
    inventoryItems: [
      {
        inventoryCode: "BRK-215",
        inventoryName: "브레이크디스크",
        requestQuantity: 50,
      },
    ],
  },
  {
    requestId: "REQ-251006-10",
    requestDate: "2025-10-06 17:00",
    agency: "전주카시스템",
    agencyLocation: "전라북도 전주시",
    manager: "유성민",
    managerPosition: "기사",
    managerContact: "010-5555-2222",
    submissionDate: "2025-10-06 17:20",
    status: "미승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "ENG-101",
        inventoryName: "엔진블록",
        requestQuantity: 1,
      },
      {
        inventoryCode: "PST-112",
        inventoryName: "피스톤세트",
        requestQuantity: 4,
      },
    ],
  },
  {
    requestId: "REQ-251007-11",
    requestDate: "2025-10-07 09:00",
    agency: "용인오토월드",
    agencyLocation: "경기도 용인시",
    manager: "박서연",
    managerPosition: "팀장",
    managerContact: "010-4321-5678",
    submissionDate: "2025-10-07 09:30",
    status: "승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "BLT-401",
        inventoryName: "벨트세트",
        requestQuantity: 6,
      },
      {
        inventoryCode: "FLT-305",
        inventoryName: "오일필터",
        requestQuantity: 12,
      },
    ],
  },
  {
    requestId: "REQ-251007-12",
    requestDate: "2025-10-07 14:00",
    agency: "제주카센터",
    agencyLocation: "제주특별자치도 제주시",
    manager: "홍지윤",
    managerPosition: "점장",
    managerContact: "010-9090-5050",
    submissionDate: "2025-10-07 14:30",
    status: "반려",
    remarks: "납기 지연 예상",
    inventoryItems: [
      {
        inventoryCode: "OIL-203",
        inventoryName: "오일필터",
        requestQuantity: 25,
      },
    ],
  },
  {
    requestId: "REQ-251008-13",
    requestDate: "2025-10-08 11:15",
    agency: "안산모터스",
    agencyLocation: "경기도 안산시",
    manager: "류하은",
    managerPosition: "대리",
    managerContact: "010-3535-7878",
    submissionDate: "2025-10-08 11:40",
    status: "승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "AIR-202",
        inventoryName: "에어필터",
        requestQuantity: 8,
      },
      {
        inventoryCode: "ENG-220",
        inventoryName: "연료펌프",
        requestQuantity: 3,
      },
    ],
  },
  {
    requestId: "REQ-251008-14",
    requestDate: "2025-10-08 16:00",
    agency: "세종오토",
    agencyLocation: "세종특별자치시",
    manager: "장도윤",
    managerPosition: "과장",
    managerContact: "010-2222-6666",
    submissionDate: "2025-10-08 16:30",
    status: "미승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "SPK-501",
        inventoryName: "스파크플러그",
        requestQuantity: 16,
      },
    ],
  },
  {
    requestId: "REQ-251009-15",
    requestDate: "2025-10-09 10:00",
    agency: "경기카서비스",
    agencyLocation: "경기도 성남시",
    manager: "백승우",
    managerPosition: "매니저",
    managerContact: "010-1000-2222",
    submissionDate: "2025-10-09 10:20",
    status: "승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "OIL-203",
        inventoryName: "오일필터",
        requestQuantity: 30,
      },
      {
        inventoryCode: "FLT-305",
        inventoryName: "연료필터",
        requestQuantity: 12,
      },
    ],
  },
  {
    requestId: "REQ-251010-16",
    requestDate: "2025-10-10 09:15",
    agency: "강릉모터라인",
    agencyLocation: "강원도 강릉시",
    manager: "이채린",
    managerPosition: "대리",
    managerContact: "010-4455-1122",
    submissionDate: "2025-10-10 09:40",
    status: "승인",
    remarks: "정기 교체용",
    inventoryItems: [
      {
        inventoryCode: "BRK-210",
        inventoryName: "브레이크패드",
        requestQuantity: 12,
      },
    ],
  },
  {
    requestId: "REQ-251011-17",
    requestDate: "2025-10-11 10:00",
    agency: "포항카테크",
    agencyLocation: "경상북도 포항시",
    manager: "윤지민",
    managerPosition: "팀장",
    managerContact: "010-2323-4545",
    submissionDate: "2025-10-11 10:25",
    status: "승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "BLT-401",
        inventoryName: "벨트세트",
        requestQuantity: 10,
      },
    ],
  },
  {
    requestId: "REQ-251012-18",
    requestDate: "2025-10-12 09:20",
    agency: "춘천오토플라자",
    agencyLocation: "강원도 춘천시",
    manager: "김태희",
    managerPosition: "매니저",
    managerContact: "010-6666-2222",
    submissionDate: "2025-10-12 09:40",
    status: "반려",
    remarks: "부품 단종",
    inventoryItems: [
      {
        inventoryCode: "CRK-301",
        inventoryName: "크랭크샤프트",
        requestQuantity: 1,
      },
    ],
  },
  {
    requestId: "REQ-251013-19",
    requestDate: "2025-10-13 13:40",
    agency: "천안카서비스",
    agencyLocation: "충청남도 천안시",
    manager: "조유진",
    managerPosition: "기사",
    managerContact: "010-3333-4444",
    submissionDate: "2025-10-13 14:00",
    status: "승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "ENG-101",
        inventoryName: "엔진블록",
        requestQuantity: 2,
      },
      {
        inventoryCode: "FLT-305",
        inventoryName: "연료필터",
        requestQuantity: 8,
      },
    ],
  },
  {
    requestId: "REQ-251014-20",
    requestDate: "2025-10-14 11:10",
    agency: "목포자동차부품상사",
    agencyLocation: "전라남도 목포시",
    manager: "박찬혁",
    managerPosition: "대리",
    managerContact: "010-1212-7878",
    submissionDate: "2025-10-14 11:30",
    status: "승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "CAB-204",
        inventoryName: "캐빈필터",
        requestQuantity: 7,
      },
    ],
  },
  {
    requestId: "REQ-251015-21",
    requestDate: "2025-10-15 15:00",
    agency: "고양모터스",
    agencyLocation: "경기도 고양시",
    manager: "이재훈",
    managerPosition: "팀장",
    managerContact: "010-1414-7878",
    submissionDate: "2025-10-15 15:25",
    status: "미승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "OIL-203",
        inventoryName: "오일필터",
        requestQuantity: 20,
      },
    ],
  },
  {
    requestId: "REQ-251016-22",
    requestDate: "2025-10-16 09:00",
    agency: "의정부카테크",
    agencyLocation: "경기도 의정부시",
    manager: "한서진",
    managerPosition: "과장",
    managerContact: "010-6767-9898",
    submissionDate: "2025-10-16 09:30",
    status: "승인",
    remarks: "정기 점검",
    inventoryItems: [
      {
        inventoryCode: "AIR-202",
        inventoryName: "에어필터",
        requestQuantity: 15,
      },
      {
        inventoryCode: "CAB-204",
        inventoryName: "캐빈필터",
        requestQuantity: 15,
      },
    ],
  },
  {
    requestId: "REQ-251017-23",
    requestDate: "2025-10-17 13:20",
    agency: "김해모터센터",
    agencyLocation: "경상남도 김해시",
    manager: "이도윤",
    managerPosition: "매니저",
    managerContact: "010-8080-5050",
    submissionDate: "2025-10-17 13:40",
    status: "반려",
    remarks: "재고 불일치",
    inventoryItems: [
      {
        inventoryCode: "BRK-210",
        inventoryName: "브레이크패드",
        requestQuantity: 12,
      },
    ],
  },
  {
    requestId: "REQ-251017-24",
    requestDate: "2025-10-17 16:10",
    agency: "광명오토케어",
    agencyLocation: "경기도 광명시",
    manager: "신도현",
    managerPosition: "대리",
    managerContact: "010-7777-1212",
    submissionDate: "2025-10-17 16:30",
    status: "미승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "BLT-401",
        inventoryName: "벨트세트",
        requestQuantity: 4,
      },
      {
        inventoryCode: "OIL-203",
        inventoryName: "오일필터",
        requestQuantity: 10,
      },
    ],
  },
  {
    requestId: "REQ-251018-25",
    requestDate: "2025-10-18 09:05",
    agency: "성북카서비스",
    agencyLocation: "서울특별시 성북구",
    manager: "오세훈",
    managerPosition: "기사",
    managerContact: "010-9898-3434",
    submissionDate: "2025-10-18 09:40",
    status: "미승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "BRK-210",
        inventoryName: "브레이크패드",
        requestQuantity: 6,
      },
    ],
  },
  {
    requestId: "REQ-251018-26",
    requestDate: "2025-10-18 14:25",
    agency: "부천모터스",
    agencyLocation: "경기도 부천시",
    manager: "김수아",
    managerPosition: "팀장",
    managerContact: "010-5555-1616",
    submissionDate: "2025-10-18 14:55",
    status: "미승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "ENG-220",
        inventoryName: "연료펌프",
        requestQuantity: 2,
      },
      {
        inventoryCode: "AIR-202",
        inventoryName: "에어필터",
        requestQuantity: 6,
      },
    ],
  },
  {
    requestId: "REQ-251019-27",
    requestDate: "2025-10-19 10:15",
    agency: "동탄오토월드",
    agencyLocation: "경기도 화성시",
    manager: "박도윤",
    managerPosition: "과장",
    managerContact: "010-2222-1515",
    submissionDate: "2025-10-19 10:40",
    status: "미승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "SPK-501",
        inventoryName: "스파크플러그",
        requestQuantity: 24,
      },
    ],
  },
  {
    requestId: "REQ-251019-28",
    requestDate: "2025-10-19 16:45",
    agency: "광양카테크",
    agencyLocation: "전라남도 광양시",
    manager: "최민재",
    managerPosition: "주임",
    managerContact: "010-3434-5656",
    submissionDate: "2025-10-19 17:05",
    status: "미승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "RAD-701",
        inventoryName: "라디에이터",
        requestQuantity: 1,
      },
      {
        inventoryCode: "WTR-602",
        inventoryName: "워터펌프",
        requestQuantity: 1,
      },
    ],
  },
  {
    requestId: "REQ-251020-29",
    requestDate: "2025-10-20 09:35",
    agency: "마포오토하우스",
    agencyLocation: "서울특별시 마포구",
    manager: "정가온",
    managerPosition: "대리",
    managerContact: "010-3030-2020",
    submissionDate: "2025-10-20 09:55",
    status: "미승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "FLT-305",
        inventoryName: "연료필터",
        requestQuantity: 10,
      },
    ],
  },
  {
    requestId: "REQ-251020-30",
    requestDate: "2025-10-20 13:50",
    agency: "구미모터샵",
    agencyLocation: "경상북도 구미시",
    manager: "서지우",
    managerPosition: "매니저",
    managerContact: "010-2626-9090",
    submissionDate: "2025-10-20 14:10",
    status: "미승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "PST-112",
        inventoryName: "피스톤세트",
        requestQuantity: 2,
      },
      {
        inventoryCode: "CRK-301",
        inventoryName: "크랭크샤프트",
        requestQuantity: 1,
      },
    ],
  },
  {
    requestId: "REQ-251021-31",
    requestDate: "2025-10-21 08:55",
    agency: "성동카서비스",
    agencyLocation: "서울특별시 성동구",
    manager: "남하율",
    managerPosition: "팀장",
    managerContact: "010-1717-5858",
    submissionDate: "2025-10-21 09:15",
    status: "미승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "CAB-204",
        inventoryName: "캐빈필터",
        requestQuantity: 12,
      },
    ],
  },
  {
    requestId: "REQ-251021-32",
    requestDate: "2025-10-21 15:30",
    agency: "김포오토케어",
    agencyLocation: "경기도 김포시",
    manager: "이성진",
    managerPosition: "기사",
    managerContact: "010-4646-7474",
    submissionDate: "2025-10-21 15:55",
    status: "미승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "BRK-215",
        inventoryName: "브레이크디스크",
        requestQuantity: 6,
      },
    ],
  },
  {
    requestId: "REQ-251022-33",
    requestDate: "2025-10-22 11:05",
    agency: "진주카센터",
    agencyLocation: "경상남도 진주시",
    manager: "장서현",
    managerPosition: "과장",
    managerContact: "010-9090-1313",
    submissionDate: "2025-10-22 11:25",
    status: "미승인",
    remarks: "",
    inventoryItems: [
      {
        inventoryCode: "ENG-101",
        inventoryName: "엔진블록",
        requestQuantity: 1,
      },
    ],
  },
];

// API 함수
export async function fetchRequestRecords(): Promise<RequestRecord[]> {
  // return (await axios.get("/api/request/records")).data;
  return requestRecords;
}
