import type { OutboundRecord } from "./OutboundTypes";

// --- query keys ---
export const outboundKeys = {
  records: ["outbound", "records"] as const,
};

// 목데이터
export const mockRecords: OutboundRecord[] = [
  {
    outboundId: "OUT1-250101-001",
    issuedDate: "2025-01-01",
    expectedDeliveryDate: "2025-01-03",
    receiptDate: "2025-01-01",
    destination: "서울 대리점",
    manager: "김도윤",
    managerPosition: "물류담당",
    managerContact: "doyoon.kim@autoparts.co.kr",
    status: "대기",
    deliveryFactory: "창고 1",
    remarks: "긴급 출고 요청",
    inventoryItems: [
      {
        inventoryCode: "PRT-BRK-001",
        inventoryName: "브레이크 패드 세트",
        outboundQuantity: 40,
      },
    ],
  },
  {
    outboundId: "OUT2-250102-002",
    issuedDate: "2025-01-02",
    expectedDeliveryDate: "2025-01-04",
    receiptDate: "2025-01-02",
    destination: "부산 대리점",
    manager: "이민호",
    managerPosition: "창고관리자",
    managerContact: "minho.lee@autoparts.co.kr",
    status: "진행중",
    deliveryFactory: "창고 2",
    remarks: "부산 지역 출고",
    inventoryItems: [
      {
        inventoryCode: "PRT-TIR-004",
        inventoryName: "타이어 18인치",
        outboundQuantity: 80,
      },
    ],
  },
  {
    outboundId: "OUT3-250103-003",
    issuedDate: "2025-01-03",
    expectedDeliveryDate: "2025-01-05",
    receiptDate: "2025-01-03",
    destination: "대전 대리점",
    manager: "박수진",
    managerPosition: "물류주임",
    managerContact: "sujin.park@autoparts.co.kr",
    status: "완료",
    deliveryFactory: "창고 3",
    remarks: "출고 완료",
    inventoryItems: [
      {
        inventoryCode: "PRT-BAT-008",
        inventoryName: "배터리 12V",
        outboundQuantity: 25,
      },
    ],
  },
  {
    outboundId: "OUT4-250104-004",
    issuedDate: "2025-01-04",
    expectedDeliveryDate: "2025-01-06",
    receiptDate: "2025-01-04",
    destination: "인천 대리점",
    manager: "최지훈",
    managerPosition: "출고담당",
    managerContact: "jihun.choi@autoparts.co.kr",
    status: "진행중",
    deliveryFactory: "창고 4",
    remarks: "인천 출고 진행",
    inventoryItems: [
      {
        inventoryCode: "PRT-LGT-011",
        inventoryName: "전조등 램프",
        outboundQuantity: 120,
      },
    ],
  },
  {
    outboundId: "OUT1-250105-005",
    issuedDate: "2025-01-05",
    expectedDeliveryDate: "2025-01-07",
    receiptDate: "2025-01-05",
    destination: "광주 대리점",
    manager: "한서준",
    managerPosition: "팀장",
    managerContact: "seojun.han@autoparts.co.kr",
    status: "대기",
    deliveryFactory: "창고 1",
    remarks: "예비 부품 출고",
    inventoryItems: [
      {
        inventoryCode: "PRT-PLG-007",
        inventoryName: "점화 플러그",
        outboundQuantity: 150,
      },
    ],
  },
  {
    outboundId: "OUT2-250106-006",
    issuedDate: "2025-01-06",
    expectedDeliveryDate: "2025-01-08",
    receiptDate: "2025-01-06",
    destination: "대구 대리점",
    manager: "윤하늘",
    managerPosition: "물류보조",
    managerContact: "haneul.yoon@autoparts.co.kr",
    status: "완료",
    deliveryFactory: "창고 2",
    remarks: "정비용 출고 완료",
    inventoryItems: [
      {
        inventoryCode: "PRT-FUL-009",
        inventoryName: "연료 필터",
        outboundQuantity: 60,
      },
    ],
  },
  {
    outboundId: "OUT3-250107-007",
    issuedDate: "2025-01-07",
    expectedDeliveryDate: "2025-01-09",
    receiptDate: "2025-01-07",
    destination: "수원 대리점",
    manager: "오태양",
    managerPosition: "배송담당",
    managerContact: "taeyang.oh@autoparts.co.kr",
    status: "진행중",
    deliveryFactory: "창고 3",
    remarks: "정기 출고",
    inventoryItems: [
      {
        inventoryCode: "PRT-OLI-002",
        inventoryName: "엔진 오일 필터",
        outboundQuantity: 90,
      },
    ],
  },
  {
    outboundId: "OUT4-250108-008",
    issuedDate: "2025-01-08",
    expectedDeliveryDate: "2025-01-10",
    receiptDate: "2025-01-08",
    destination: "창원 대리점",
    manager: "장유진",
    managerPosition: "물류주임",
    managerContact: "yujin.jang@autoparts.co.kr",
    status: "대기",
    deliveryFactory: "창고 4",
    remarks: "출고 대기 중",
    inventoryItems: [
      {
        inventoryCode: "PRT-BEL-005",
        inventoryName: "엔진 벨트 세트",
        outboundQuantity: 45,
      },
    ],
  },
  {
    outboundId: "OUT1-250109-009",
    issuedDate: "2025-01-09",
    expectedDeliveryDate: "2025-01-11",
    receiptDate: "2025-01-09",
    destination: "전주 대리점",
    manager: "배유리",
    managerPosition: "팀원",
    managerContact: "yuri.bae@autoparts.co.kr",
    status: "진행중",
    deliveryFactory: "창고 1",
    remarks: "정기 공급",
    inventoryItems: [
      {
        inventoryCode: "PRT-SPR-010",
        inventoryName: "서스펜션 스프링",
        outboundQuantity: 30,
      },
    ],
  },
  {
    outboundId: "OUT2-250110-010",
    issuedDate: "2025-01-10",
    expectedDeliveryDate: "2025-01-12",
    receiptDate: "2025-01-10",
    destination: "울산 대리점",
    manager: "문지후",
    managerPosition: "창고담당",
    managerContact: "jihuu.moon@autoparts.co.kr",
    status: "완료",
    deliveryFactory: "창고 2",
    remarks: "출고 완료",
    inventoryItems: [
      {
        inventoryCode: "PRT-WIP-006",
        inventoryName: "와이퍼 블레이드",
        outboundQuantity: 200,
      },
    ],
  },
  {
    outboundId: "OUT3-250111-011",
    issuedDate: "2025-01-11",
    expectedDeliveryDate: "2025-01-13",
    receiptDate: "2025-01-11",
    destination: "제주 대리점",
    manager: "이서율",
    managerPosition: "물류보조",
    managerContact: "seoyul.lee@autoparts.co.kr",
    status: "대기",
    deliveryFactory: "창고 3",
    remarks: "도서지역 출고",
    inventoryItems: [
      {
        inventoryCode: "PRT-CBL-012",
        inventoryName: "점화 케이블",
        outboundQuantity: 80,
      },
    ],
  },
  {
    outboundId: "OUT4-250112-012",
    issuedDate: "2025-01-12",
    expectedDeliveryDate: "2025-01-14",
    receiptDate: "2025-01-12",
    destination: "포항 대리점",
    manager: "정하늘",
    managerPosition: "운송주임",
    managerContact: "haneul.jung@autoparts.co.kr",
    status: "진행중",
    deliveryFactory: "창고 4",
    remarks: "정기 출고 진행중",
    inventoryItems: [
      {
        inventoryCode: "PRT-EXH-013",
        inventoryName: "배기 머플러",
        outboundQuantity: 15,
      },
    ],
  },
  {
    outboundId: "OUT1-250113-013",
    issuedDate: "2025-01-13",
    expectedDeliveryDate: "2025-01-15",
    receiptDate: "2025-01-13",
    destination: "용인 대리점",
    manager: "조하윤",
    managerPosition: "배송팀",
    managerContact: "hayoon.jo@autoparts.co.kr",
    status: "완료",
    deliveryFactory: "창고 1",
    remarks: "용인 지역 출고",
    inventoryItems: [
      {
        inventoryCode: "PRT-FAN-014",
        inventoryName: "라디에이터 팬",
        outboundQuantity: 18,
      },
    ],
  },
  {
    outboundId: "OUT2-250114-014",
    issuedDate: "2025-01-14",
    expectedDeliveryDate: "2025-01-16",
    receiptDate: "2025-01-14",
    destination: "춘천 대리점",
    manager: "서준혁",
    managerPosition: "물류보조",
    managerContact: "junhyuk.seo@autoparts.co.kr",
    status: "진행중",
    deliveryFactory: "창고 2",
    remarks: "출고 준비 중",
    inventoryItems: [
      {
        inventoryCode: "PRT-ABS-015",
        inventoryName: "ABS 센서",
        outboundQuantity: 35,
      },
    ],
  },
  {
    outboundId: "OUT3-250115-015",
    issuedDate: "2025-01-15",
    expectedDeliveryDate: "2025-01-17",
    receiptDate: "2025-01-15",
    destination: "평택 대리점",
    manager: "차유리",
    managerPosition: "물류담당",
    managerContact: "yuri.cha@autoparts.co.kr",
    status: "대기",
    deliveryFactory: "창고 3",
    remarks: "부품 대기 중",
    inventoryItems: [
      {
        inventoryCode: "PRT-COI-016",
        inventoryName: "점화 코일",
        outboundQuantity: 40,
      },
    ],
  },
  {
    outboundId: "OUT4-250116-016",
    issuedDate: "2025-01-16",
    expectedDeliveryDate: "2025-01-18",
    receiptDate: "2025-01-16",
    destination: "세종 대리점",
    manager: "권도연",
    managerPosition: "물류주임",
    managerContact: "doyeon.kwon@autoparts.co.kr",
    status: "완료",
    deliveryFactory: "창고 4",
    remarks: "정상 출고 완료",
    inventoryItems: [
      {
        inventoryCode: "PRT-AIR-017",
        inventoryName: "에어필터",
        outboundQuantity: 55,
      },
    ],
  },
  {
    outboundId: "OUT1-250117-017",
    issuedDate: "2025-01-17",
    expectedDeliveryDate: "2025-01-19",
    receiptDate: "2025-01-17",
    destination: "고양 대리점",
    manager: "박재민",
    managerPosition: "팀원",
    managerContact: "jaemin.park@autoparts.co.kr",
    status: "진행중",
    deliveryFactory: "창고 1",
    remarks: "정기 출고 중",
    inventoryItems: [
      {
        inventoryCode: "PRT-PMP-018",
        inventoryName: "워터 펌프",
        outboundQuantity: 22,
      },
    ],
  },
  {
    outboundId: "OUT2-250118-018",
    issuedDate: "2025-01-18",
    expectedDeliveryDate: "2025-01-20",
    receiptDate: "2025-01-18",
    destination: "김해 대리점",
    manager: "이도겸",
    managerPosition: "물류보조",
    managerContact: "dokyeom.lee@autoparts.co.kr",
    status: "대기",
    deliveryFactory: "창고 2",
    remarks: "대기 출고",
    inventoryItems: [
      {
        inventoryCode: "PRT-SNS-019",
        inventoryName: "산소 센서",
        outboundQuantity: 25,
      },
    ],
  },
  {
    outboundId: "OUT3-250119-019",
    issuedDate: "2025-01-19",
    expectedDeliveryDate: "2025-01-21",
    receiptDate: "2025-01-19",
    destination: "수원 대리점",
    manager: "김세아",
    managerPosition: "배송주임",
    managerContact: "sea.kim@autoparts.co.kr",
    status: "완료",
    deliveryFactory: "창고 3",
    remarks: "납품 완료",
    inventoryItems: [
      {
        inventoryCode: "PRT-ALT-020",
        inventoryName: "알터네이터",
        outboundQuantity: 10,
      },
    ],
  },
  {
    outboundId: "OUT4-250120-020",
    issuedDate: "2025-01-20",
    expectedDeliveryDate: "2025-01-22",
    receiptDate: "2025-01-20",
    destination: "천안 대리점",
    manager: "이서진",
    managerPosition: "물류담당",
    managerContact: "seojin.lee@autoparts.co.kr",
    status: "진행중",
    deliveryFactory: "창고 4",
    remarks: "천안 출고 중",
    inventoryItems: [
      {
        inventoryCode: "PRT-CLT-021",
        inventoryName: "클러치 디스크",
        outboundQuantity: 32,
      },
    ],
  },
  {
    outboundId: "OUT1-250121-021",
    issuedDate: "2025-01-21",
    expectedDeliveryDate: "2025-01-23",
    receiptDate: "2025-01-21",
    destination: "원주 대리점",
    manager: "남유진",
    managerPosition: "배송팀",
    managerContact: "yujin.nam@autoparts.co.kr",
    status: "대기",
    deliveryFactory: "창고 1",
    remarks: "출고 대기 중",
    inventoryItems: [
      {
        inventoryCode: "PRT-MIR-022",
        inventoryName: "사이드 미러",
        outboundQuantity: 12,
      },
    ],
  },
  {
    outboundId: "OUT2-250122-022",
    issuedDate: "2025-01-22",
    expectedDeliveryDate: "2025-01-24",
    receiptDate: "2025-01-22",
    destination: "광명 대리점",
    manager: "정태윤",
    managerPosition: "물류팀",
    managerContact: "taeyoon.jung@autoparts.co.kr",
    status: "완료",
    deliveryFactory: "창고 2",
    remarks: "광명 출고 완료",
    inventoryItems: [
      {
        inventoryCode: "PRT-DRS-023",
        inventoryName: "도어 스위치",
        outboundQuantity: 28,
      },
    ],
  },
  {
    outboundId: "OUT3-250123-023",
    issuedDate: "2025-01-23",
    expectedDeliveryDate: "2025-01-25",
    receiptDate: "2025-01-23",
    destination: "성남 대리점",
    manager: "김하린",
    managerPosition: "배송담당",
    managerContact: "harin.kim@autoparts.co.kr",
    status: "진행중",
    deliveryFactory: "창고 3",
    remarks: "성남 출고 중",
    inventoryItems: [
      {
        inventoryCode: "PRT-HOS-024",
        inventoryName: "냉각수 호스",
        outboundQuantity: 50,
      },
    ],
  },
  {
    outboundId: "OUT4-250124-024",
    issuedDate: "2025-01-24",
    expectedDeliveryDate: "2025-01-26",
    receiptDate: "2025-01-24",
    destination: "안산 대리점",
    manager: "오지훈",
    managerPosition: "물류보조",
    managerContact: "jihoon.oh@autoparts.co.kr",
    status: "대기",
    deliveryFactory: "창고 4",
    remarks: "예비 부품 출고 예정",
    inventoryItems: [
      {
        inventoryCode: "PRT-TRM-025",
        inventoryName: "도어 트림 패널",
        outboundQuantity: 14,
      },
    ],
  },
  {
    outboundId: "OUT1-250125-025",
    issuedDate: "2025-01-25",
    expectedDeliveryDate: "2025-01-27",
    receiptDate: "2025-01-25",
    destination: "의정부 대리점",
    manager: "임다온",
    managerPosition: "물류담당",
    managerContact: "daeon.lim@autoparts.co.kr",
    status: "완료",
    deliveryFactory: "창고 1",
    remarks: "출고 정상 처리",
    inventoryItems: [
      {
        inventoryCode: "PRT-AXL-026",
        inventoryName: "드라이브 샤프트",
        outboundQuantity: 8,
      },
    ],
  },
  {
    outboundId: "OUT2-250126-026",
    issuedDate: "2025-01-26",
    expectedDeliveryDate: "2025-01-28",
    receiptDate: "2025-01-26",
    destination: "부천 대리점",
    manager: "송은재",
    managerPosition: "배송팀",
    managerContact: "eunjae.song@autoparts.co.kr",
    status: "진행중",
    deliveryFactory: "창고 2",
    remarks: "부천 출고",
    inventoryItems: [
      {
        inventoryCode: "PRT-CAL-027",
        inventoryName: "브레이크 캘리퍼",
        outboundQuantity: 16,
      },
    ],
  },
  {
    outboundId: "OUT3-250127-027",
    issuedDate: "2025-01-27",
    expectedDeliveryDate: "2025-01-29",
    receiptDate: "2025-01-27",
    destination: "청주 대리점",
    manager: "노지안",
    managerPosition: "물류주임",
    managerContact: "jian.noh@autoparts.co.kr",
    status: "대기",
    deliveryFactory: "창고 3",
    remarks: "청주 대리점 보충",
    inventoryItems: [
      {
        inventoryCode: "PRT-RAD-028",
        inventoryName: "라디에이터",
        outboundQuantity: 11,
      },
    ],
  },
  {
    outboundId: "OUT4-250128-028",
    issuedDate: "2025-01-28",
    expectedDeliveryDate: "2025-01-30",
    receiptDate: "2025-01-28",
    destination: "경산 대리점",
    manager: "권도현",
    managerPosition: "창고관리자",
    managerContact: "dohyun.kwon@autoparts.co.kr",
    status: "완료",
    deliveryFactory: "창고 4",
    remarks: "납품 완료",
    inventoryItems: [
      {
        inventoryCode: "PRT-STM-029",
        inventoryName: "스티어링 모터",
        outboundQuantity: 9,
      },
    ],
  },
  {
    outboundId: "OUT1-250129-029",
    issuedDate: "2025-01-29",
    expectedDeliveryDate: "2025-01-31",
    receiptDate: "2025-01-29",
    destination: "목포 대리점",
    manager: "위다연",
    managerPosition: "물류담당",
    managerContact: "dayeon.wi@autoparts.co.kr",
    status: "진행중",
    deliveryFactory: "창고 1",
    remarks: "목포 출고",
    inventoryItems: [
      {
        inventoryCode: "PRT-ECU-030",
        inventoryName: "엔진 제어 유닛(ECU)",
        outboundQuantity: 6,
      },
    ],
  },
  {
    outboundId: "OUT2-250130-030",
    issuedDate: "2025-01-30",
    expectedDeliveryDate: "2025-02-01",
    receiptDate: "2025-01-30",
    destination: "제천 대리점",
    manager: "백서준",
    managerPosition: "배송담당",
    managerContact: "seojun.baek@autoparts.co.kr",
    status: "대기",
    deliveryFactory: "창고 2",
    remarks: "월말 출고",
    inventoryItems: [
      {
        inventoryCode: "PRT-TPM-031",
        inventoryName: "TPMS 센서",
        outboundQuantity: 26,
      },
    ],
  },
];

// --- API 함수 ---
export async function fetchOutboundRecords(): Promise<OutboundRecord[]> {
  // return (await axios.get("/api/outbound/records")).data;
  return mockRecords;
}
